### ISSUE TITLE
Attempt to index local "L" (a nil value)

### ISSUE THREAD

**Issue by skeetcha** [migeyel/ecnet#1]
I'm trying to run the script on a [CraftOS terminal](https://craftos-pc.cc) but I am getting the error referenced in the title on line 278 in the minimized file. I downloaded it using wget on the terminal. I'm not entirely sure why this error occurred as L definitely exists on that line. Perhaps there is something else going on?

**Comment by migeyel** [comment]
It seems like you're calling `ecnet.wrap(modem)` with `modem` being `nil`. If you used `modem = peripheral.find("modem")` then this probably means that there are no modems attached to the computer.

I'm surprised that CraftOS-PC even works with this, last time I checked it failed on transforming tables into entropy on the startup phase.

Recently I've been reworking the entire application and internal primitives, so work on this version is pretty much nonexistent in favor of the newer API, though that takes time. I thought that I had released a newer version but it seems like it got stuck somewhere and is sitting there untouched in the develop branch.
